### PR TITLE
Ensure that npm is not run in production mode

### PR DESCRIPTION
**Pull request by nullobject**
This PR fixes a mistake I made when [previously](https://github.com/conversation/babushka-deps/pull/49) trying to fix up our npm install process.

When we install packages we want to force npm to *not* run in production mode. This is because we also require development dependencies to be installed on our production servers.

### CODE REVIEW

**Comment by yob** [comment]
So this should install packages from both `dependencies` and `devDependencies`?

**Comment by nullobject** [comment]
> So this should install packages from both dependencies and devDependencies?

Correct. Previously we were getting around this by chucking all our dependencies into `devDependencies`. But I don't think that is the best solution.

**Comment by nullobject** [comment]
`--production=false` forces npm to install dev dependencies, even if `NODE_ENV=production`.

See [this thread](https://github.com/npm/npm/issues/6803#issuecomment-75621914) for more info.

**Comment by yob** [comment]
Cool. I might apply this change to staging and run a deploy to confirm it works as we expect

**Comment by yob** [comment]
Unfortunately the deploy to staging failed.

```
        remote:   common:on deploy {
          remote:     on deploy {
          remote:       conversation:set up newrelic configuration {
          remote:         Writing newrelic config
          remote:       } ✓ conversation:set up newrelic configuration
          remote:       common:when path changed {
          remote:         5 changes within #<Babushka::Parameter:47125096280300 path: /(app|lib|vendor)\/assets\/|config\/locales\/tc_js...>:
          remote:         1     2       app/assets/javascripts/views/draft_link_tooltip_view.coffee
          remote:         4     0       config/locales/tc_js/es.yml
          remote:         1     0       config/locales/tc_js/fr.yml
          remote:         1     0       package.json
          remote:         0     778     vendor/assets/javascripts/clipboard.js
          remote:         conversation:webpack compile during deploy {
          remote:           conversation:npm packages installed {
          remote:             meet {
          remote:             }
          remote:           } ✗ conversation:npm packages installed
          remote:         } ✗ conversation:webpack compile during deploy
          remote:       } ✗ common:when path changed
          remote:     } ✗ on deploy
          remote:   } ✗ common:on deploy
          remote: } ✗ common:post-receive.git_hook
          remote: You can view a more detailed log at '/srv/http/theconversation.com/.babushka/logs/common:post-receive.git_hook'.
          To 206.51.240.238:~/current
             0c4b2a8f92..4431755ada  HEAD -> master

**Comment by nullobject** [comment]
I checked, it failed because `npm ls` found extraneous packages. 🤔

**Comment by nickbrowne** [comment]
> Correct. Previously we were getting around this by chucking all our dependencies into devDependencies. But I don't think that is the best solution.

We've just been following the suggestions in https://github.com/webpack/webpack/issues/520, where "runtime" dependencies go in `dependencies`, and non-runtime dependencies go in `devDependencies`. The naming of the two dependency groups is unfortunate, but to me it makes sense to keep non-runtime dependencies separate.

**Comment by yob** [comment]
> I checked, it failed because npm ls found extraneous packages.

So it would've failed under the old dep as well?

**Comment by nullobject** [comment]
> So it would've failed under the old dep as well?

No. We were forcing `--dev` before which doesn't check for extraneous packages.

We could do a `npm prune` before we run the `npm ls --production`?

That way any old packages would be removed before we check and install new ones.

**Comment by nickbrowne** [comment]
I'm not sure, but here's what the old code was doing

```
dep 'npm development packages installed', :path do
  met? {
    output = raw_shell('npm ls --dev', :cd => path)
    output.ok?
  }
  meet {
    shell('npm install --only=dev', :cd => path)
  }
end
```

**Comment by nullobject** [comment]
@nickbrowne That code would *never* install anything in `dependencies`. Only `devDependencies` were being installed. That's why I changed it.

**Comment by nickbrowne** [comment]
Yup, but it was intentionally done that way

**Comment by yob** [comment]
It seems like we might need to have a philosophical discussion about how we want to treat `dependencies` and `devDependencies`.

Given tc is currently unshippable, I vote for reverting back to the old style (`npm install --only=dev`) while we have that discussion.

**Comment by nullobject** [comment]
@yob Can we try it one more time with my tweak first?

**Comment by yob** [comment]
I think I'd rather just revert. I'm not across the `dependencies`/`devDependencies` issues and it seems like both approaches can work, but we should agree on a consistent approach before continuing down this path.

**Comment by nullobject** [comment]
Ok. TC already has `lazysizes` in `dependencies`, so we will probably need to move that into `devDependencies` to keep it working.

**Comment by yob** [comment]
Ok. I'll open a PR on TC hat does that - can you prepare the revert to babushka?

**Comment by nullobject** [comment]
Sure, reverting...

**Comment by nullobject** [comment]
I'm not going to change anything else with this, now that we're going to dockerise our apps.

**Pull request closed without merging**
