### PR TITLE
TC-715 Log to correct statsd port

### PR DESCRIPTION
**Pull request by nickbrowne**
dogstatsd runs on port 8126

### CODE REVIEW

**Comment by jameshill** [comment]
Interesting, so I initially thought it was the port as well... and then opened up IRB on prod.

and did the following:

```ruby
require 'socket'
=> true
>> UDPSocket.new.send("test.unicorn.workers:3|g", 0, '127.0.0.1', 8126)
=> 24
```

then had a look on datadog, and haven't seen them appear 🤔 

Metric_Explorer___Datadog


Perhaps i'm forgetting something?

**Comment by nickbrowne** [comment]
It's there, it just takes a few mins for the datadog agent to flush all the statsd stuff (it batches a bunch of them together) https://app.datadoghq.com/metric/explorer?live=true&page=0&is_auto=false&from_ts=1553134595672&to_ts=1553138195672&tile_size=m&exp_metric=test.unicorn.workers&exp_scope=&exp_agg=avg&exp_row_type=metric

**Comment by jameshill** [comment]
ahh damnit...

**Comment by jameshill** [comment]
Well... that's good news.

**Comment by yob** [comment]
📈📈📈📈

**Comment by jameshill** [comment]
@yob oh hello there... yes.. public repo and all..

soon it'll all be in ansible.

**Pull request merged**
