### PR TITLE
Require Spanish dictionaries for aspell

### PR DESCRIPTION
**Pull request by eleanorakh**
We are preparing to [add Spanish support](https://github.com/conversation/tc/pull/7336) for our spell checker, which relies on this aspell dictionary.
I think this needs to be added on the thanks, but I'm not sure how to do that?

### CODE REVIEW

**Comment by eleanorakh** [comment]
[include Spanish dictionary in CI](https://trello.com/c/EI1OWwX6/9148-include-spanish-dictionary-in-ci)

**Comment by nickbrowne** [comment]
The "correct" way is probably to re-run provisioning, but I tend to just re-run the individual dep on each machine once the change is on master.

**Comment by yob** [comment]
I ran this on tank2 and it worked perfectly:

```
# babushka "conversation:aspell dictionary.lib"
conversation:aspell dictionary.lib {
  apt {
    package manager {
      'apt-get' runs from /usr/bin.
    } ✓ package manager
    apt source {
    } ✓ apt source
    apt source {
    } ✓ apt source
  } ✓ apt
  conversation:aspell.bin {
    'aspell' runs from /usr/bin.
  } ✓ conversation:aspell.bin
  ✓ system has aspell-en deb
  ✓ system has aspell-fr deb
  ✓ system has aspell-id deb
  system doesn't have aspell-es deb
  meet {
    The apt package lists are 2 days old. Updating... done.
    Installing aspell-en, aspell-fr, aspell-id, aspell-es and libaspell-dev via apt... done.
  }
  ✓ system has aspell-en deb
  ✓ system has aspell-fr deb
  ✓ system has aspell-id deb
  ✓ system has aspell-es deb
  ✓ system has libaspell-dev deb
} ✓ conversation:aspell dictionary.lib
```

**Comment by yob** [comment]
I've now run this on all ci, staging and prod boxes

**Pull request merged**
